In [ ]:
from XML_utils import *

import jsonlines, regex
import pandas as pd

In [2]:
years = "O_R__1879-1884"
#years = "O_R__1885-1889"
#years = "O_R__1890-1894"
#years = "O_R__1895+1905-1907" 
#years = "O_R__1908-1909+1930" 
#years = "O_R__1931-1934" 
#years = "O_R__1935-1937" 
#years = "O_R__1938-1939_1945-1946_Stad"
#years = "O_R__1946_Buiten_1947-1949"

## Create clean text for GPT

In [3]:
data_dir = f"g:\My Drive\Overlijdensdata Curaçao 1831-1950\Transkribus HTR output\{years}\page"
texts, metadata, corrected_texts, info, regions = read_files(data_dir)

Nr of baseline swaps: 1805

In [ ]:
def clean_string(text):
    text = regex.sub(r"-\n(?=[a-z])", r"", text) # ver-beteren -> verbeteren
    text = regex.sub(r"-\n(?=[A-Z])", r"-", text) # Bert-Jan -> Bert-Jan
    text = regex.sub(r"\n", " ", text) # remove all remaining newlines
    text = regex.sub(r"\s+", " ", text) # change all multiple whitespace characters to a single space
    return text

In [23]:
df = pd.DataFrame(texts.keys(), columns=['ID'])
df['TEXT'] = texts.values()
df['TEXT_GPT'] = df['TEXT'].apply(clean_string)
df.head()

,ID,TEXT,TEXT_GPT
0,O.R. 1895 Buiten 2e distr. 001,No. 1.\nHeden den Tweeden Januari des Jaars\nE...,No. 1. Heden den Tweeden Januari des Jaars Een...
1,O.R. 1895 Buiten 2e distr. 002,No. 2.\nHeden den Tweeden Januari des Jaars\nE...,No. 2. Heden den Tweeden Januari des Jaars Een...
2,O.R. 1895 Buiten 2e distr. 003,No. 5\nHeden den derden Januari des\nEen duize...,No. 5 Heden den derden Januari des Een duizend...
3,O.R. 1895 Buiten 2e distr. 004,honderd achten\nApp\n3\nNo. 4.\nHeden den Zeve...,honderd achten App 3 No. 4. Heden den Zevenden...
4,O.R. 1895 Buiten 2e distr. 005,No.\nHeden den Vijftienden Januari des Jaars\n...,No. Heden den Vijftienden Januari des Jaars Ee...

In [24]:
df.to_excel(f'G:\My Drive\Overlijdensdata Curaçao 1831-1950\Transkribus HTR output\{years}\{years}.xlsx')

## Create input files for GPT

In [10]:
years = ["O_R__1879-1884", "O_R__1885-1889", "O_R__1890-1894", "O_R__1895+1905-1907", "O_R__1908-1909+1930", "O_R__1931-1934", "O_R__1935-1937", "O_R__1938-1939_1945-1946_Stad", "O_R__1946_Buiten_1947-1949"]

In [11]:
all_data = pd.DataFrame()

for year in years:
    data_file = f'G:\My Drive\Overlijdensdata Curaçao 1831-1950\Transkribus HTR output\{year}\{year}.xlsx'
    data = pd.read_excel(data_file, index_col=0)
    all_data = pd.concat([all_data,data])

In [27]:
all_data = all_data.sort_values(by='ID').reset_index(drop=True)
all_data

,ID,TEXT,TEXT_GPT
0,O.R. 1879 Buiten 2e distr. 001,No. 1.\nHeden den Eersten Januari des Jaars\nE...,No. 1. Heden den Eersten Januari des Jaars Een...
1,O.R. 1879 Buiten 2e distr. 002,No. 2.\nHeden den zesden Januari des Jaars\nEe...,No. 2. Heden den zesden Januari des Jaars Een ...
2,O.R. 1879 Buiten 2e distr. 003,No. 3.\nHeden den Zevenden January des Jaars\n...,No. 3. Heden den Zevenden January des Jaars Ee...
3,O.R. 1879 Buiten 2e distr. 004,No. 6\nHeden den Negentienden Januari des Jaar...,No. 6 Heden den Negentienden Januari des Jaars...
4,O.R. 1879 Buiten 2e distr. 005,No. 5\nHeden den Twintigsten Januari des Jaars...,No. 5 Heden den Twintigsten Januari des Jaars ...
...,...,...,...
23934,O.R. 1949 Stad 633,"Nr. 633\nveertig\nRenvooi, zomede de doorha-\n...","Nr. 633 veertig Renvooi, zomede de doorhaling ..."
23935,O.R. 1949 Stad 634,"Nr. 634\nveertig\nRenvooi, nemede de doorha-\n...","Nr. 634 veertig Renvooi, nemede de doorhaling ..."
23936,O.R. 1949 Stad 635,"Nr. 635\nveertig\nRenvooi, mede de door\nhalin...","Nr. 635 veertig Renvooi, mede de door haling v..."
23937,O.R. 1949 Stad 636,Nr. 636\nveertig\nRenvooi zomede de\ndoorhalin...,Nr. 636 veertig Renvooi zomede de doorhaling v...
23938,O.R. 1949 Stad 637,"Nr. 657\nveertig\nRenvooi, komede de door\nhal...","Nr. 657 veertig Renvooi, komede de door haling..."

In [28]:
all_data.to_excel(f'G:\My Drive\Overlijdensdata Curaçao 1831-1950\Transkribus HTR output\Transkribus HTR output.xlsx')

### Retrieve all Transkribus HTR output

In [12]:
all_data = pd.read_excel(f'G:\My Drive\Overlijdensdata Curaçao 1831-1950\Transkribus HTR output\Transkribus HTR output.xlsx', index_col=0)
all_data

,ID,TEXT,TEXT_GPT
0,O.R. 1879 Buiten 2e distr. 001,No. 1.\nHeden den Eersten Januari des Jaars\nE...,No. 1. Heden den Eersten Januari des Jaars Een...
1,O.R. 1879 Buiten 2e distr. 002,No. 2.\nHeden den zesden Januari des Jaars\nEe...,No. 2. Heden den zesden Januari des Jaars Een ...
2,O.R. 1879 Buiten 2e distr. 003,No. 3.\nHeden den Zevenden January des Jaars\n...,No. 3. Heden den Zevenden January des Jaars Ee...
3,O.R. 1879 Buiten 2e distr. 004,No. 6\nHeden den Negentienden Januari des Jaar...,No. 6 Heden den Negentienden Januari des Jaars...
4,O.R. 1879 Buiten 2e distr. 005,No. 5\nHeden den Twintigsten Januari des Jaars...,No. 5 Heden den Twintigsten Januari des Jaars ...
...,...,...,...
23934,O.R. 1949 Stad 633,"Nr. 633\nveertig\nRenvooi, zomede de doorha-\n...","Nr. 633 veertig Renvooi, zomede de doorhaling ..."
23935,O.R. 1949 Stad 634,"Nr. 634\nveertig\nRenvooi, nemede de doorha-\n...","Nr. 634 veertig Renvooi, nemede de doorhaling ..."
23936,O.R. 1949 Stad 635,"Nr. 635\nveertig\nRenvooi, mede de door\nhalin...","Nr. 635 veertig Renvooi, mede de door haling v..."
23937,O.R. 1949 Stad 636,Nr. 636\nveertig\nRenvooi zomede de\ndoorhalin...,Nr. 636 veertig Renvooi zomede de doorhaling v...
23938,O.R. 1949 Stad 637,"Nr. 657\nveertig\nRenvooi, komede de door\nhal...","Nr. 657 veertig Renvooi, komede de door haling..."

In [30]:
data_1879_1881 = all_data[all_data['ID'].str.contains(r'1879|1880|1881')]
data_1879_1881

,ID,TEXT,TEXT_GPT
0,O.R. 1879 Buiten 2e distr. 001,No. 1.\nHeden den Eersten Januari des Jaars\nE...,No. 1. Heden den Eersten Januari des Jaars Een...
1,O.R. 1879 Buiten 2e distr. 002,No. 2.\nHeden den zesden Januari des Jaars\nEe...,No. 2. Heden den zesden Januari des Jaars Een ...
2,O.R. 1879 Buiten 2e distr. 003,No. 3.\nHeden den Zevenden January des Jaars\n...,No. 3. Heden den Zevenden January des Jaars Ee...
3,O.R. 1879 Buiten 2e distr. 004,No. 6\nHeden den Negentienden Januari des Jaar...,No. 6 Heden den Negentienden Januari des Jaars...
4,O.R. 1879 Buiten 2e distr. 005,No. 5\nHeden den Twintigsten Januari des Jaars...,No. 5 Heden den Twintigsten Januari des Jaars ...
...,...,...,...
1532,O.R. 1881 Stad 363,No. 363\nHeden den dertigsten December des Jaa...,No. 363 Heden den dertigsten December des Jaar...
1533,O.R. 1881 Stad 364,No. 364\nHeden den dertigsten December des Jaa...,No. 364 Heden den dertigsten December des Jaar...
1534,O.R. 1881 Stad 365,"""\nde\nNo. 365\nHeden den dertigsten December ...",""" de No. 365 Heden den dertigsten December des..."
1535,O.R. 1881 Stad 366,No. 366\nHeden den dertigsten December des Jaa...,No. 366 Heden den dertigsten December des Jaar...
1536,O.R. 1881 Stad 367,No. 36\ndertig December des Jaars\nHeden den E...,No. 36 dertig December des Jaars Heden den Een...

In [31]:
data_1882_1934 = all_data[all_data['ID'].str.contains(r'188[23456789]|189\d|19[012]\d|193[01234]')]
data_1882_1934

,ID,TEXT,TEXT_GPT
1537,O.R. 1882 Buiten 2e distr. 001,No. 1\nHeden den zevenden January des Jaars\nE...,No. 1 Heden den zevenden January des Jaars Een...
1538,O.R. 1882 Buiten 2e distr. 002,No. 2.\nHeden den Twaalfden Januari des Jaars\...,No. 2. Heden den Twaalfden Januari des Jaars E...
1539,O.R. 1882 Buiten 2e distr. 003,Voor de doorhaling De\ncember op den elfden\nr...,Voor de doorhaling De cember op den elfden reg...
1540,O.R. 1882 Buiten 2e distr. 004,No. 4.\nHeden den Viertienden Januari des Jaar...,No. 4. Heden den Viertienden Januari des Jaars...
1541,O.R. 1882 Buiten 2e distr. 005,No. 5.\nHeden den Dertienden January des Jaars...,No. 5. Heden den Dertienden January des Jaars ...
...,...,...,...
16067,O.R. 1934 Stad 479,No. 479\nHeden den acht en twintigsten Decembe...,No. 479 Heden den acht en twintigsten December...
16068,O.R. 1934 Stad 480,"De doorhaling van het gedrukte\nte woord ,,jar...","De doorhaling van het gedrukte te woord ,,jare..."
16069,O.R. 1934 Stad 481,No. 181\nHeden den acht en twintigsten Decembe...,No. 181 Heden den acht en twintigsten December...
16070,O.R. 1934 Stad 482,"De doorhaling van het ge-\nschreven woord ,, v...","De doorhaling van het geschreven woord ,, vere..."
16071,O.R. 1934 Stad 483,De doorhaling van de gedrukte\nwoorden in neve...,De doorhaling van de gedrukte woorden in neven...

In [32]:
data_1935_1938 = all_data[all_data['ID'].str.contains(r'193[5678]')]
data_1935_1938

,ID,TEXT,TEXT_GPT
16072,O.R. 1935 Buiten 2e distr. 001,No. 11\nHeden den vierden Januari negentienhon...,No. 11 Heden den vierden Januari negentienhond...
16073,O.R. 1935 Buiten 2e distr. 002,No. 2\nHeden den vijfden Januari negentienhond...,No. 2 Heden den vijfden Januari negentienhonde...
16074,O.R. 1935 Buiten 2e distr. 003,No. 5\nHeden den zevenden Januari negentienhon...,No. 5 Heden den zevenden Januari negentienhond...
16075,O.R. 1935 Buiten 2e distr. 004,No. 4\nHeden den zevenden Januari negentienhon...,No. 4 Heden den zevenden Januari negentienhond...
16076,O.R. 1935 Buiten 2e distr. 005,No. 5\nHeden den zevenden Januari negentienhon...,No. 5 Heden den zevenden Januari negentienhond...
...,...,...,...
19180,O.R. 1938 Stad 546,No. 646\nHeden den een en dertigsten December ...,No. 646 Heden den een en dertigsten December n...
19181,O.R. 1938 Stad 547,No. 517\nHeden den een en dertigsten December ...,No. 517 Heden den een en dertigsten December n...
19182,O.R. 1938 Stad 548,No. 578\nDe doorhaling van\nacht gedrukte woor...,No. 578 De doorhaling van acht gedrukte woorde...
19183,O.R. 1938 Stad 549,No. 579\nHeden den een en dertigsten December ...,No. 579 Heden den een en dertigsten December n...
19184,O.R. 1938 Stad 550,No. 550\nHeden den een en dertigsten December ...,No. 550 Heden den een en dertigsten December n...

In [33]:
data_1939_1950 = all_data[all_data['ID'].str.contains(r'1939|19[45]\d')]
data_1939_1950

,ID,TEXT,TEXT_GPT
19185,O.R. 1939 Buiten 2e distr. 001,Nr. 1\nHeden den twaalfden Januari\nnegentien ...,Nr. 1 Heden den twaalfden Januari negentien ho...
19186,O.R. 1939 Buiten 2e distr. 002,Nr. 2.\nden\nRenvooi alsmede beken\nvoeging go...,Nr. 2. den Renvooi alsmede beken voeging goedg...
19187,O.R. 1939 Buiten 2e distr. 003,Nr. 3\nHeden den achttienden Januari\nnegentie...,Nr. 3 Heden den achttienden Januari negentienh...
19188,O.R. 1939 Buiten 2e distr. 005,Nr. 3\nHeden den acht en twintigsten Januari\n...,Nr. 3 Heden den acht en twintigsten Januari ne...
19189,O.R. 1939 Buiten 2e distr. 006,Nr. 6\ndoorhaling van twee ge-\nakte woorden g...,Nr. 6 doorhaling van twee geakte woorden goedg...
...,...,...,...
23934,O.R. 1949 Stad 633,"Nr. 633\nveertig\nRenvooi, zomede de doorha-\n...","Nr. 633 veertig Renvooi, zomede de doorhaling ..."
23935,O.R. 1949 Stad 634,"Nr. 634\nveertig\nRenvooi, nemede de doorha-\n...","Nr. 634 veertig Renvooi, nemede de doorhaling ..."
23936,O.R. 1949 Stad 635,"Nr. 635\nveertig\nRenvooi, mede de door\nhalin...","Nr. 635 veertig Renvooi, mede de door haling v..."
23937,O.R. 1949 Stad 636,Nr. 636\nveertig\nRenvooi zomede de\ndoorhalin...,Nr. 636 veertig Renvooi zomede de doorhaling v...
23938,O.R. 1949 Stad 637,"Nr. 657\nveertig\nRenvooi, komede de door\nhal...","Nr. 657 veertig Renvooi, komede de door haling..."

In [34]:
prompt_1879_1934 = """You are a Dutch entity extraction tool for Curaçao death certificates. Your task is to extract entities from persons mentioned in the death certificate. There are two formats, normal certificates and stillborn certificates.

In general:
- In front of the certificate can be written some modifications, such as a name or date change. It also describes which words are approved to be strikethrough. After determining all entities, go back to this text and see if you need to make any modifications. 
- If an entity is not mentioned in the text, fill in '#'.
- Write down dates in dd-mm-yyyy format. If only a year is given, write only the year yyyy. If only the month and year are written, write mm-yyyy. If an estimation is given or it is explicitly written that a certain date is unknown, fill in this exact string from the text, like 'onbekend' or 'vermoedelijk in het jaar 1800'.
- Write down time in hh:mm format. So 'tien ure des morgens' is '10:00'.
- Write down age in digits, so 'acht jaren' is '8'. However, keep estimations, so 'acht jaren, naar schatting' is '8 jaren, naar schatting' and 'circa acht jaren' is 'circa 8 jaren' and 'acht jaren, naar gissing' is '8 jaren, naar gissing'.
- A profession of a person is often right behind the person's name (except for 'overleden' which means the person has deceased). 
- When written 'zonder beroep', 'beroep onbekend' or 'beroep geen', this means the person does not have a profession, fill in 'zonder beroep', 'onbekend' or 'geen' in these cases. 
- Some professions have spelling errors, fill in exactly how it is written in the certificate.
- SEX can often be derived from words like zoon, dochter, echtgenoote(e) or weduwe/weduwnaar. Fill in 'm' or 'v'.
- The options for MARITAL_STATUS are ongehuwd, gehuwd, weduwe/weduwnaar, gescheiden, or #.
- If a father, mother or partner has deceased, this is indicated as 'overleden' or 'wijlen' behind the person. If the person has an address, this person is alive. Fill in 'overleden', 'in leven', 'onbekend' or '#'. Use 'onbekend' when this is mentioned and '#' if nothing is mentioned.

Hints for the locations of the entities:
- Heden den CERTIFICATE_DATE 
- De personen van NAME_INFORMANT_1 van beroep PROFESSION_INFORMANT_1 oud AGE_INFORMANT_1 wonende ... en NAME_INFORMANT_2 van beroep PROFESSION_INFORMANT_2 oud AGE_INFORMANT_2
- dewelke aangifte hebben gedaan ... op den DATE_OF_DEATH te TIME_OF_DEATH
- overleden is NAME in den ouderdom van AGE van beroep PROFESSION
- echtgenoot(e) van PARTNER_INFO | gehuwd (geweest)? met PARTNER_INFO
- (zoon/dochter) van FATHER_INFO en MOTHER_INFO | (zoon/dochter) van MOTHER_INFO | (zoon/dochter) van ouders onbekend
- zynde geboren PLACE_OF_BIRTH den DATE_OF_BIRTH

If, spelling errors allowed, the certificate contains the word 'levensloos' and a phrase like 'een kind ter wereld gebracht' or 'een kind uit' or 'is bevallen van een kind', this is a stillborn certificate. This case, the following rules override the others:
- DATE_OF_BIRTH is CERTIFICATE_DATE.
- There is no partner.
- een kind ter wereld gebracht door MOTHER_INFO | een kind uit MOTHER_INFO | MOTHER_INFO is bevallen van een kind.
- Father is optional, often given like: echtgenoote van FATHER_INFO.
- NAME has first name 'levensloos' and prefix+lastname from the father (or mother if no father is given).

Given a death certificate text, you return your answer about the deceased person in the following json format:
{"STILLBORN_CERTIFICATE": "True/False", "CERTIFICATE_DATE": "", "NAME_INFORMANT_1": "", "PROFESSION_INFORMANT_1": "", "AGE_INFORMANT_1": "", "NAME_INFORMANT_2": "", "PROFESSION_INFORMANT_2": "","AGE_INFORMANT_2": "", "DATE_OF_DEATH": "", "TIME_OF_DEATH": "", "NAME": "", "AGE": "", "PROFESSION": "", "PLACE_OF_BIRTH": "", "DATE_OF_BIRTH": "", "SEX": "", "MARITAL_STATUS": "", "FATHER_NAME": "", "FATHER_DECEASED": "", "FATHER_PROFESSION": "", "MOTHER_NAME": "", "MOTHER_DECEASED": "", "MOTHER_PROFESSION": "", "PARTNER_NAME": "", "PARTNER_DECEASED": "", "PARTNER_PROFESSION": ""}"""

In [17]:
prompt_1935_1938 = """You are a Dutch entity extraction tool for Curaçao death certificates. Your task is to extract entities from persons mentioned in the death certificate. There are two formats, normal certificates and stillborn certificates.

In general:
- In front of the certificate can be written some modifications, such as a name or date change. It also describes which words are approved to be strikethrough. After determining all entities, go back to this text and see if you need to make any modifications. 
- If an entity is not mentioned in the text, fill in '#'.
- Write down dates in dd-mm-yyyy format. If only a year is given, write only the year yyyy. If only the month and year are written, write mm-yyyy. If an estimation is given or it is explicitly written that a certain date is unknown, fill in this exact string from the text, like 'onbekend' or 'vermoedelijk in het jaar 1800'.
- Write down time in hh:mm format. So 'tien ure des morgens' is '10:00'.
- Write down age in digits, so 'acht jaren' is '8'. However, keep estimations, so 'acht jaren, naar schatting' is '8 jaren, naar schatting' and 'circa acht jaren' is 'circa 8 jaren' and 'acht jaren, naar gissing' is '8 jaren, naar gissing'.
- A profession of a person is often right behind the person's name (except for 'overleden' which means the person has deceased). 
- When written 'zonder beroep', 'beroep onbekend' or 'beroep geen', this means the person does not have a profession, fill in 'zonder beroep', 'onbekend' or 'geen' in these cases. 
- Some professions have spelling errors, fill in exactly how it is written in the certificate.
- SEX can often be derived from words like zoon, dochter, echtgenoote(e) or weduwe/weduwnaar. Fill in 'm' or 'v'.
- The options for MARITAL_STATUS are ongehuwd, gehuwd, weduwe/weduwnaar, gescheiden, or #.
- If a father, mother or partner has deceased, this is indicated as 'overleden' or 'wijlen' behind the person. If the person has an address, this person is alive. Fill in 'overleden', 'in leven', 'onbekend' or '#'. Use 'onbekend' when this is mentioned and '#' if nothing is mentioned.

Hints for the locations of the entities:
- Heden den CERTIFICATE_DATE 
- op Curacao NAME_INFORMANT_1 oud AGE_INFORMANT_1 van beroep PROFESSION_INFORMANT_1 wonende
- die op grond van eigen wetenschap verklaarde dat ... op den DATE_OF_DEATH ten TIME_OF_DEATH
- overleden is NAME in den ouderdom van AGE PROFESSION
- echtgenoot(e) van PARTNER_INFO | gehuwd (geweest)? met PARTNER_INFO
- (zoon/dochter) van FATHER_INFO en MOTHER_INFO | (zoon/dochter) van MOTHER_INFO | (zoon/dochter) van ouders onbekend
- zynde geboren PLACE_OF_BIRTH den DATE_OF_BIRTH

If, spelling errors allowed, the certificate contains the word 'levensloos' and a phrase like 'een kind ter wereld gebracht' or 'een kind uit' or 'is bevallen van een kind', this is a stillborn certificate. This case, the following rules override the others:
- DATE_OF_BIRTH is CERTIFICATE_DATE.
- There is no partner.
- een kind ter wereld gebracht door MOTHER_INFO | een kind uit MOTHER_INFO | MOTHER_INFO is bevallen van een kind.
- Father is optional, often given like: echtgenoote van FATHER_INFO.
- NAME has first name 'levensloos' and prefix+lastname from the father (or mother if no father is given).

Given a death certificate text, you return your answer about the deceased person in the following json format:
{"STILLBORN_CERTIFICATE": "True/False", "CERTIFICATE_DATE": "", "NAME_INFORMANT_1": "", "PROFESSION_INFORMANT_1": "", "AGE_INFORMANT_1": "", "DATE_OF_DEATH": "", "TIME_OF_DEATH": "", "NAME": "", "AGE": "", "PROFESSION": "", "PLACE_OF_BIRTH": "", "DATE_OF_BIRTH": "", "SEX": "", "MARITAL_STATUS": "", "FATHER_NAME": "", "FATHER_DECEASED": "", "FATHER_PROFESSION": "", "MOTHER_NAME": "", "MOTHER_DECEASED": "", "MOTHER_PROFESSION": "", "PARTNER_NAME": "", "PARTNER_DECEASED": "", "PARTNER_PROFESSION": ""}"""

In [18]:
prompt_1939_1950 = """You are a Dutch entity extraction tool for Curaçao death certificates. Your task is to extract entities from persons mentioned in the death certificate. There are two formats, normal certificates and stillborn certificates.

In general:
- In front of the certificate can be written some modifications, such as a name or date change. It also describes which words are approved to be strikethrough. After determining all entities, go back to this text and see if you need to make any modifications. 
- If an entity is not mentioned in the text, fill in '#'.
- Write down dates in dd-mm-yyyy format. If only a year is given, write only the year yyyy. If only the month and year are written, write mm-yyyy. If an estimation is given or it is explicitly written that a certain date is unknown, fill in this exact string from the text, like 'onbekend' or 'vermoedelijk in het jaar 1800'.
- The year of death can be described as 'dezes jaars', fill in the same year as the certificate year here.
- Write down time in hh:mm format. So 'tien ure des morgens' is '10:00'.
- Write down age in digits, so 'acht jaren' is '8'. However, keep estimations, so 'acht jaren, naar schatting' is '8 jaren, naar schatting' and 'circa acht jaren' is 'circa 8 jaren' and 'acht jaren, naar gissing' is '8 jaren, naar gissing'.
- A profession of a person is often right behind the person's name (except for 'overleden' which means the person has deceased).
- When written 'zonder beroep', 'beroep onbekend' or 'beroep geen', this means the person does not have a profession, fill in 'zonder beroep', 'onbekend' or 'geen' in these cases. 
- Some professions have spelling errors, fill in exactly how it is written in the certificate.
- SEX can often be derived from words like zoon, dochter, echtgenoote(e) or weduwe/weduwnaar. Fill in 'm' or 'v'.
- The options for MARITAL_STATUS are ongehuwd, gehuwd, weduwe/weduwnaar, gescheiden, or #.
- If a father, mother or partner has deceased, this is indicated as 'overleden' or 'wijlen' behind the person. If the person has an address, this person is alive. Fill in 'overleden', 'in leven', 'onbekend' or '#'. Use 'onbekend' when this is mentioned and '#' if nothing is mentioned.

Hints for the locations of the entities:
- Heden den CERTIFICATE_DATE 
- op Curacao NAME_INFORMANT_1 oud AGE_INFORMANT_1 van beroep PROFESSION_INFORMANT_1 wonende
- die verklaarde ... dat op den DATE_OF_DEATH des TIME_OF_DEATH
- alhier is overleden NAME in den ouderdom van AGE PROFESSION
- geboren PLACE_OF_BIRTH den DATE_OF_BIRTH
- echtgenoot(e) van PARTNER_INFO | gehuwd (geweest)? met PARTNER_INFO
- (zoon/dochter) van FATHER_INFO en MOTHER_INFO | (zoon/dochter) van MOTHER_INFO | (zoon/dochter) van ouders onbekend

If, spelling errors allowed, the certificate contains the word 'levensloos' and a phrase like 'een kind ter wereld gebracht' or 'een kind uit' or 'is bevallen van een kind', this is a stillborn certificate. This case, the following rules override the others:
- DATE_OF_BIRTH is CERTIFICATE_DATE.
- There is no partner.
- een kind ter wereld gebracht door MOTHER_INFO | een kind uit MOTHER_INFO | MOTHER_INFO is bevallen van een kind.
- Father is optional, often given like: echtgenoote van FATHER_INFO.
- NAME has first name 'levensloos' and prefix+lastname from the father (or mother if no father is given).

Given a death certificate text, you return your answer about the deceased person in the following json format:
{"STILLBORN_CERTIFICATE": "True/False", "CERTIFICATE_DATE": "", "NAME_INFORMANT_1": "", "PROFESSION_INFORMANT_1": "", "AGE_INFORMANT_1": "", "DATE_OF_DEATH": "", "TIME_OF_DEATH": "", "NAME": "", "AGE": "", "PROFESSION": "", "PLACE_OF_BIRTH": "", "DATE_OF_BIRTH": "", "SEX": "", "MARITAL_STATUS": "", "FATHER_NAME": "", "FATHER_DECEASED": "", "FATHER_PROFESSION": "", "MOTHER_NAME": "", "MOTHER_DECEASED": "", "MOTHER_PROFESSION": "", "PARTNER_NAME": "", "PARTNER_DECEASED": "", "PARTNER_PROFESSION": ""}"""

In [35]:
def create_jsonl(years, data, prompt):
    lines = []
    # create test sample size 10
    #data = data.sample(n=10, random_state=22)
    for nr, idx in enumerate(data.index):
            messages=[
                    {"role": "system", "content": f"""{prompt}"""},
                    {"role": "user", "content": f"""{data['TEXT_GPT'].loc[idx]}"""}, 
            ]
            line = {"custom_id": data['ID'].loc[idx], "method": "POST", "url": "/v1/chat/completions", "body": {"model": "gpt-4-0125-preview", "temperature":0, "response_format":{"type":"json_object"}, "messages": messages}}
            lines.append(line)
    with jsonlines.open(f'data_gpt/{years}.jsonl', mode='w') as writer:
        for line in lines:
            writer.write(line)

In [47]:
#create_jsonl("1879-1881", data_1879_1881, prompt_1879_1934)
#create_jsonl("1882-1934", data_1882_1934, prompt_1879_1934)
#create_jsonl("1935-1938", data_1935_1938, prompt_1935_1938)
#create_jsonl("1939-1950", data_1939_1950, prompt_1939_1950)